configurations:
  - sources:
      - ./.
    templates:
      - ./.sourcery.stencil
    args:
      autoMockableImports: [
        "CoreLocation",
        "SharedDomain"
      ]
    output:
      ../SharedDomainMocks/Mocks/Mocks.generated.swift
