excluded:
  - Carthage
  - Pods
  - vendor
  - DataLayer/Providers/GraphQLProvider/.build
  - DataLayer/Toolkits/RocketToolkit/Sources/RocketToolkit/NetworkModels/Apollo
  - DataLayer/Toolkits/RocketToolkit/Sources/RocketToolkitMocks
  - DomainLayer/SharedDomain/.build
  
indentation: 2
cyclomatic_complexity: 10
file_length: 200
function_body_length: 50
function_parameter_count: 5

line_length:
  warning: 140
  ignores_comments: true

trailing_whitespace:
  ignores_empty_lines: true

disabled_rules:
  - identifier_name

opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - function_default_parameter_at_end
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - literal_expression_end_indentation
  - let_var_whitespace
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - sorted_imports
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

analyzer_rules:
  - unused_import
  - unused_declaration
